export const ColumnCenterCarList = [
    {
        headerName: 'SỐ CCCD',
        field: 'ownerId',
        align: 'left',
        headerAlign: 'left',
        flex:1,
    },
    {
        headerName: 'BIỂN SỐ',
        field: 'licensePlate',
        align: 'left',
        headerAlign:'left',
        flex:1,
    },
    {
        headerName: 'HÃNG XE',
        field: 'brand',
        align: 'left',
        headerAlign:'left',
        flex:1,
    },
    {
        headerName: 'DÒNG XE',
        field: 'model',
        align: 'left',
        headerAlign:'left',
        flex:1,
    },
    {
        headerName: 'TRUNG TÂM',
        field: 'centreName',
        align: 'left',
        headerAlign:'left',
        flex:1,
    },
    {
        headerName: 'THÀNH PHỐ',
        field: 'centreCity',
        align: 'left',
        headerAlign:'left',
        flex:1,
    },
    {
        headerName: 'NGÀY ĐĂNG KIỂM',
        field: 'registrationDate',
        align: 'left',
        headerAlign:'left',
        flex:1,
    },
];
